# Generated by Django 4.1.5 on 2023-03-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Available',
            field=models.BooleanField(default=True),
        ),
    ]
