# Generated by Django 4.1.5 on 2023-03-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_products_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Add',
            field=models.BooleanField(default=False),
        ),
    ]
